### ISSUE TITLE
`cmd/baize-server` 里面的内容是不是跟 `cmd/baize-executor` 搞反了

### ISSUE THREAD

**Issue by btwiuse** [dashjay/baize#2]
https://github.com/dashjay/baize/blob/e31878f7564a3c91c6bfe13f700fae4f41915728/cmd/baize-server/main.go#L44

为啥 `baize-server` 里面调用的是 BazelExecutor

https://github.com/dashjay/baize/blob/e31878f7564a3c91c6bfe13f700fae4f41915728/cmd/baize-executor/main.go#L30
`baize-executor` 调用的是 BazelServer 捏

**Comment by dashjay** [comment]
我还没开发完所有的内容到目前为止，用了一下 buildbuddy 发现很多问题，所以正在研究 cache 部分，看能不能针对小文件做一下优化，还没开始开发主程序。

**Comment by btwiuse** [comment]
原来如此...
